# Generated by Django 5.1.7 on 2025-03-31 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreconresult',
            name='mt_transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_recon', to='recon.rawmt940transaction'),
        ),
        migrations.AlterField(
            model_name='autoreconresult',
            name='sap_document_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_recon', to='recon.rawsappayment'),
        ),
        migrations.AlterField(
            model_name='manualreconresult',
            name='mt_transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_recon', to='recon.rawmt940transaction'),
        ),
        migrations.AlterField(
            model_name='manualreconresult',
            name='sap_document_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_recon', to='recon.rawsappayment'),
        ),
    ]
