# Generated by Django 5.1.7 on 2025-03-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_alter_autoreconresult_mt_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreconresult',
            name='approve_tmst',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
