# Generated by Django 5.1.7 on 2025-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_alter_autoreconresult_approve_tmst'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmt940transaction',
            name='is_manually_reconned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawsappayment',
            name='is_manually_reconned',
            field=models.BooleanField(default=False),
        ),
    ]
